package eu.skypotion.kits.model;

import eu.skypotion.mongo.codec.ItemStackCodec;
import eu.skypotion.util.builder.ItemBuilder;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

import java.util.List;
import java.util.concurrent.TimeUnit;

@Getter
@AllArgsConstructor
@FieldDefaults(level = lombok.AccessLevel.PRIVATE, makeFinal = true)
public enum Kit {

    SPIELER("spieler", "§7Spieler§8-§7Kit", null, false, TimeUnit.MINUTES.toMillis(5), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(2), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(16), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    GUARDIAN("guardian", "§b§lG§3§lUARDIAN§8-§7Kit", "skypotion.kit.guardian", false, TimeUnit.MINUTES.toMillis(15), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(4), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(16), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    VORTEX("vortex", "§e§lVORT§6§lΣ§e§lX§8-§7Kit", "skypotion.kit.vortex", false, TimeUnit.MINUTES.toMillis(25), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 1).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(6), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(16), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    ULTRA("ultra", "§5§lU§d§lL§5§lT§d§lR§5§lA§8-§7Kit", "skypotion.kit.ultra", false, TimeUnit.MINUTES.toMillis(35), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(6), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(16), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    EXECUTE("execute", "§d§lE§4§lX§b§lE§a§lC§6§lU§9§lT§2§lE§8-§7Kit", "skypotion.kit.execute", false, TimeUnit.MINUTES.toMillis(45), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(8), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(32), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    MASTER("master", "§a§lMASTER§8-§7Kit", "skypotion.kit.master", false, TimeUnit.MINUTES.toMillis(55), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    EXTREME("extreme", "§2§lΣ§a§lX§2§lT§a§lR§2§lE§a§lM§2§lE§8-§7Kit", "skypotion.kit.extreme", false, TimeUnit.MINUTES.toMillis(65), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    VENUS("venus", "§5§lV§dΣ§5§lNUS§8-§7Kit", "skypotion.kit.venus", false, TimeUnit.MINUTES.toMillis(75), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    CHAMPION("champion", "§b§lC§3§lH§b§lA§3§lM§b§lP§3§lI§b§lO§3§lN§8-§7Kit", "skypotion.kit.champion", false, TimeUnit.MINUTES.toMillis(85), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    HERO("hero", "§c§lH§4§lΣ§c§lRO§8-§7Kit", "skypotion.kit.hero", false, TimeUnit.MINUTES.toMillis(95), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    KING("king", "§e⚔ §6§lK§e§lI§6§lN§e§lG §6⚔§8-§7Kit", "skypotion.kit.king", false, TimeUnit.MINUTES.toMillis(105), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 4).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    POTION("potion", "§5§lPO§d§lTI§5§lON§8-§7Kit", "skypotion.kit.potion", false, TimeUnit.MINUTES.toMillis(120), List.of(ItemBuilder.of(Material.IRON_HELMET).withName("§8» §cEisenhelm").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_CHESTPLATE).withName("§8» §cEisenbrustplatte").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_LEGGINGS).withName("§8» §cEisenbeinschutz").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_BOOTS).withName("§8» §cEisenschuhe").withEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.IRON_SWORD).withName("§8» §cEisenschwert").withEnchantment(Enchantment.DAMAGE_ALL, 5).withEnchantment(Enchantment.DURABILITY, 3), ItemBuilder.of(Material.BOW).withName("§8» §cBogen").withEnchantment(Enchantment.ARROW_DAMAGE, 1), ItemBuilder.of(Material.GOLDEN_APPLE).withName("§8» §cGoldener Apfel").withAmount(16), ItemBuilder.of(Material.ENDER_PEARL).withName("§8» §cEnderperle").withAmount(64), ItemBuilder.of(Material.ARROW).withName("§8» §cPfeil").withAmount(64))),
    ;

    String name;
    String displayName;
    String permission;

    boolean limited;
    long cooldown;

    List<ItemStack> items;

    public static final Kit[] VALUES = values();

    public static Kit getByName(String name) {
        for (Kit kit : VALUES) {
            if (kit.getName().equalsIgnoreCase(name)) {
                return kit;
            }
        }
        return null;
    }

}
